<%@ Page Title="Registro de Cambios" Language="C#" MasterPageFile="~/Master.Master" AutoEventWireup="true" CodeBehind="rCambios.aspx.cs" Inherits="CasaDeCambio.Registros.rCambios" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="Contenido" runat="server">
    <div class="panel panel-primary">
        <div class="panel-body">
              <div class="form-horizontal col-md-12" role="form">
                   <div class="form-group row">
                    <label for="ID" class="col-sm-1 col-form-label">ID</label>
                    <div class="col-md-1 col-sm-2 col-xs-4">
                        <asp:TextBox type="number" ID="IDTextBox" runat="server" min=0 class="form-control input-sm"></asp:TextBox>
                    </div>
                    <div class="col-md-2 col-sm-2 col-xs-4">
                         <asp:LinkButton ID="BuscarButton" CssClass="btn btn-dark btn-block btn-md" CausesValidation="false" runat="server" Text="Buscar" ></asp:LinkButton>
                    </div>    
                    <label for="Fecha" class="col-xs-1 col-form-label">Fecha</label>
                    <div class="col-md-3">
                        <asp:TextBox ID="FechaTextBox" type="date" runat="server" Class="form-control input-sm"></asp:TextBox>
                        <asp:RequiredFieldValidator ID="RFVFecha" runat="server" MaxLength="200" ControlToValidate="FechaTextBox" ErrorMessage="Fecha no valida" ForeColor="Black" Display="None" SetFocusOnError="True" ToolTip="Campo obligatorio"></asp:RequiredFieldValidator>
                    </div>
                </div>
                  <div class="form-group row">
                 <label for="Persona" class="col-sm-1 col-form-label">Persona</label>
                     <div class="col-lg-3">
                         <asp:TextBox runat="server" CssClass="form-control input-sm" ID="PersonaTextBox"></asp:TextBox>
                         <asp:RequiredFieldValidator ID="RFVPersona" runat="server" MaxLength="100" ControlToValidate="PersonaTextBox" ErrorMessage="Persona no valida" ForeColor="Black" Display="None" SetFocusOnError="True"></asp:RequiredFieldValidator>
                     </div>
                 </div>

                   <div class="form-group row">
                    <label for="Dinero" class="col-sm-1 col-form-label">Dinero</label>
                    <div class="col-lg-3">
                        <asp:TextBox ID="DineroTextBox" runat="server" class="form-control input-sm"></asp:TextBox>
                        <asp:RequiredFieldValidator ID="RFVDinero" runat="server" MaxLength="200" ControlToValidate="DineroTextBox" ErrorMessage="Cantidad de dinero invalida" ForeColor="Black" Display="None" SetFocusOnError="True" ToolTip="Campo obligatorio"></asp:RequiredFieldValidator>
                    </div>
                    <label for="Divisa" class="col-xs-1 col-form-label">Divisa</label>
                    <div class="col-lg-3">
                        <asp:DropDownList ID="DivisaDropDown" runat="server" Class="form-control input-sm"></asp:DropDownList>
                    </div>
                     <div class="col-sm-2">
                        <asp:LinkButton runat="server" ID="AgregarGrid" CssClass="btn btn-outline-info btn-md" Text="+"></asp:LinkButton>
                    </div>
                </div>
                  <asp:GridView ID="Grid" CssClass=" col-md-offset-4 col-sm-offset-4" runat="server" DataKeyNames="DetalleId" AllowPaging="true" PageSize="10" ShowHeaderWhenEmpty="true" AutoGenerateDeleteButton="true" CellPadding="4" ForeColor="#333333" GridLines="None" Width="1000px" AutoGenerateColumns="false">                         
                    <Columns>
                        <asp:BoundField DataField="Cantidad" HeaderText="Cantidad" /><asp:BoundField />
                        <asp:BoundField DataField="Divisa" HeaderText="Divisa" /><asp:BoundField />
                        <asp:BoundField DataField="Cambio" HeaderText="Retorno" /><asp:BoundField />
                        <asp:BoundField DataField="Fecha" HeaderText="Fecha" /><asp:BoundField />
                    </Columns>     
                    <EmptyDataTemplate><div style="text-align:center">No hay datos en la tabla.</div></EmptyDataTemplate>
                         <AlternatingRowStyle BackColor="White" />

                            <EditRowStyle BackColor="#2461BF" />
                            <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                            <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                            <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                            <RowStyle BackColor="#EFF3FB" />
                            <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                            <SortedAscendingCellStyle BackColor="#F5F7FB" />
                            <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                            <SortedDescendingCellStyle BackColor="#E9EBEF" />
                            <SortedDescendingHeaderStyle BackColor="#4870BE" />
                </asp:GridView>
                 <br />
                 <div class="form-group row">
                 <label for="Total" class="col-sm-1 col-form-label">Total</label>
                     <div class="col-lg-3">
                         <asp:TextBox runat="server" CssClass="form-control input-sm" ID="TotalCambiadoTextBox" ReadOnly="true"></asp:TextBox>
                     </div>
                 </div>
              </div>
             <div class="col-md-5">
                <asp:ValidationSummary runat="server" ID="SummaryValidation"
                    ForeColor="red"
                    DisplayMode="List"
                    ShowSummary="true"
                    EnableClientScript="True"
                    Font-Bold="True"
                    CssClass=" alert alert-light" />
            </div>
        </div>
     <div class="panel-footer">
     <div class="text-center">
        <div class="form-group" style="display: inline-block">

              <asp:Button Text="Nuevo" class="btn btn-warning btn-sm" CausesValidation="false" style="color:#fff" runat="server" ID="NuevoButton" />
              <asp:Button Text="Guardar" class="btn btn-success btn-sm" runat="server" ID="GuardarButton"/>
              <asp:Button Text="Eliminar" class="btn btn-danger btn-sm" CausesValidation="false" runat="server" ID="EliminarButton" />

        </div>
       </div>

 </div>
        </div>
</asp:Content>
