<%@ Page Title="Registro de Cambios" Language="C#" MasterPageFile="~/Master.Master" AutoEventWireup="true" CodeBehind="rCambios.aspx.cs" Inherits="CasaDeCambio.Registros.rCambios" %>
<%@ Register assembly="Microsoft.ReportViewer.WebForms" namespace="Microsoft.Reporting.WebForms" tagprefix="rsweb" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="Contenido" runat="server">
                <asp:ScriptManager ID="ScriptManager1" runat="server"></asp:ScriptManager>
    <div class="panel panel-primary">
      <div class="panel-heading" style="font-size: 20px; color: white; padding:15px; background-color:black">CAMBIOS DE DIVISAS</div><br />
        <div class="panel-body">
              <div class="form-horizontal col-md-12" role="form">
                   <div class="form-group row">
                    <label for="ID" class="col-sm-1 col-form-label">ID</label>
                    <div class="col-md-1 col-sm-2 col-xs-4">
                        <asp:TextBox type="number" ID="IDTextBox" runat="server" min=0 class="form-control input-sm"></asp:TextBox>
                    </div>
                    <div class="col-md-2 col-sm-2 col-xs-4">
                         <asp:LinkButton ID="BuscarButton" CssClass="btn btn-dark btn-block btn-md" CausesValidation="false" runat="server" Text="Buscar" OnClick="BuscarButton_Click" ></asp:LinkButton>
                    </div>    
                    <label for="Fecha" class="col-xs-1 col-form-label">Fecha</label>
                    <div class="col-md-2">
                        <asp:TextBox ID="FechaTextBox" type="date" runat="server" Class="form-control input-sm"></asp:TextBox>
                        <asp:RequiredFieldValidator ID="RFVFecha" runat="server" MaxLength="200" ControlToValidate="FechaTextBox" ErrorMessage="Fecha no valida" ForeColor="Black" Display="None" SetFocusOnError="True" ToolTip="Campo obligatorio"></asp:RequiredFieldValidator>
                    </div>
                     <div class="col-md-2">
                        <asp:DropDownList ID="OpcionDropDown" runat="server" Class="form-control input-sm">
                            <asp:ListItem>Compra</asp:ListItem>
                            <asp:ListItem>Venta</asp:ListItem>
                         </asp:DropDownList>
                    </div>
                </div>
                  <div class="form-group row">
                 <label for="Persona" class="col-sm-1 col-form-label">Persona</label>
                     <div class="col-lg-3">
                         <asp:TextBox runat="server" CssClass="form-control input-sm" ID="PersonaTextBox"></asp:TextBox>
                         <asp:RequiredFieldValidator ID="RFVPersona" runat="server" MaxLength="100" ControlToValidate="PersonaTextBox" ErrorMessage="Persona no valida" ForeColor="Black" Display="None" SetFocusOnError="True"></asp:RequiredFieldValidator>
                     </div>
                 </div>

                   <div class="form-group row">
                    <label for="Dinero" class="col-sm-1 col-form-label">Dinero</label>
                    <div class="col-lg-2">
                        <asp:TextBox ID="DineroTextBox" runat="server" class="form-control input-sm"></asp:TextBox>
                    </div>
                    <label for="DeDivisa" class="col-xs-1 col-form-label">De</label>
                    <div class="col-lg-3">
                        <asp:DropDownList ID="DeDivisaDropDown" runat="server" Class="form-control input-sm"></asp:DropDownList>
                    </div>
                    <label for="CualDivisa" class="col-xs-1 col-form-label">A</label>
                    <div class="col-lg-3">
                        <asp:DropDownList ID="CualDivisaDropDown" runat="server" Class="form-control input-sm"></asp:DropDownList>
                    </div>
                     <div class="col-sm-2">
                        <asp:LinkButton runat="server" ID="AgregarGrid" CssClass="btn btn-outline-info btn-md" Text="+" OnClick="AgregarGrid_Click"></asp:LinkButton>
                    </div>
                </div>
                  <asp:GridView ID="Grid" CssClass=" col-md-offset-4 col-sm-offset-4" runat="server" DataKeyNames="DetalleId" AllowPaging="true" PageSize="10" ShowHeaderWhenEmpty="true" AutoGenerateDeleteButton="true" CellPadding="4" ForeColor="#333333" GridLines="None" Width="1000px" AutoGenerateColumns="false" OnPageIndexChanging="Grid_PageIndexChanging" OnRowDeleting="Grid_RowDeleting">                         
                    <Columns>
                        <asp:BoundField DataField="De" HeaderText="Dinero" /><asp:BoundField />
                        <asp:BoundField DataField="A" HeaderText="Cambio" /><asp:BoundField />
                        <asp:BoundField DataField="Fecha" HeaderText="Fecha de cambio" DataFormatString="{0:d}" /><asp:BoundField />

                    </Columns>     
                    <EmptyDataTemplate><div style="text-align:center">No hay datos en la tabla.</div></EmptyDataTemplate>
                         <AlternatingRowStyle BackColor="White" />

                            <EditRowStyle BackColor="#2461BF" />
                            <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                            <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                            <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                            <RowStyle BackColor="#EFF3FB" />
                            <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                            <SortedAscendingCellStyle BackColor="#F5F7FB" />
                            <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                            <SortedDescendingCellStyle BackColor="#E9EBEF" />
                            <SortedDescendingHeaderStyle BackColor="#4870BE" />
                </asp:GridView>
                 <br />
                 <div class="form-group row">
                 <label for="Total" class="col-sm-1 col-form-label">Total</label>
                     <div class="col-lg-3">
                         <asp:TextBox runat="server" CssClass="form-control input-sm" ID="TotalCambiadoTextBox" ReadOnly="true"></asp:TextBox>
                     </div>
                 </div>
              </div>
             <div class="col-md-5">
                <asp:ValidationSummary runat="server" ID="SummaryValidation"
                    ForeColor="red"
                    DisplayMode="List"
                    ShowSummary="true"
                    EnableClientScript="True"
                    Font-Bold="True"
                    CssClass=" alert alert-light" />
            </div>
        </div>
     <div class="panel-footer">
     <div class="text-center">
        <div class="form-group" style="display: inline-block">

              <asp:Button Text="Nuevo" class="btn btn-warning btn-offset-lg" CausesValidation="false" style="color:#fff" runat="server" ID="NuevoButton" OnClick="NuevoButton_Click" />
              <asp:Button Text="Guardar" class="btn btn-success btn-offset-lg" runat="server" ID="GuardarButton" OnClick="GuardarButton_Click"/>
               <button type="button" class="btn btn-info" data-toggle="modal" data-target=".bd-example-modal-lg">Imprimir</button>
              <asp:Button Text="Eliminar" class="btn btn-danger btn-offset-lg" CausesValidation="false" runat="server" ID="EliminarButton" OnClick="EliminarButton_Click" />
        </div>
       </div>
          <div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
               <div class="modal-dialog" style="max-width: 900px!important; min-width: 600px!important;max-height:800px!important; min-height:500px!important">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">RECIBO</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <%--Viewer--%>
                            <rsweb:ReportViewer ID="MyViewer" runat="server" ProcessingMode="Local" Height="500px" Width="800px">
                                <ServerReport ReportPath="" ReportServerUrl="" />
                            </rsweb:ReportViewer>
                        </div>
                        <div class="modal-footer">
                        </div>
                    </div>
                </div>
          </div>
 </div>
        </div>
</asp:Content>
